import { SPECIES_IDS as S } from './species.data';
import type { NatureRule } from './rules.types';

export const RESOURCE_RULES: NatureRule[] = [
  // Pollinator collapse -> crop failure -> famine. 2-3 hops from an easily-missed act.
  {
    id: 'bee_collapse',
    when: { kind: 'population', species: S.meadowBee, op: '<', value: 0.2 },
    sustainedFor: 200,
    after: 80,
    then: [{ kind: 'populationRate', species: S.berryShrub, multiplier: 0.6, durationTicks: 8_000 }],
    narrative: 'The meadow has gone quiet — no bees drone among the berry shrubs.',
    severity: 'minor',
    blamedSpecies: S.meadowBee,
  },
  {
    id: 'berry_pollination_failure',
    when: { kind: 'population', species: S.berryShrub, op: '<', value: 0.25 },
    sustainedFor: 600,
    after: 200,
    chain: ['bee_collapse'],
    then: [{ kind: 'populationRate', species: S.wildBoar, multiplier: 0.7, durationTicks: 8_000 }],
    narrative: 'The berry shrubs have failed to set fruit for a second season.',
    severity: 'notable',
    blamedSpecies: S.meadowBee,
  },
  {
    id: 'boar_famine_from_pollinator_loss',
    when: { kind: 'population', species: S.wildBoar, op: '<', value: 0.3 },
    sustainedFor: 800,
    after: 300,
    chain: ['bee_collapse', 'berry_pollination_failure'],
    then: [{ kind: 'populationShock', species: S.wildBoar, fractionDelta: -0.15 }],
    narrative: 'Word reaches the village: the boar have gone lean, and the harvest was thin too.',
    severity: 'major',
    blamedSpecies: S.meadowBee,
  },

  // Overfishing -> algal bloom -> water poisoning.
  {
    id: 'lakefish_overfished',
    when: { kind: 'population', species: S.lakeFish, op: '<', value: 0.2 },
    sustainedFor: 300,
    after: 100,
    then: [{ kind: 'populationRate', species: S.lakeAlgae, multiplier: 1.5, durationTicks: 8_000 }],
    narrative: 'The lake has been fished hard — nothing left to graze the shallows.',
    severity: 'minor',
    blamedSpecies: S.lakeFish,
  },
  {
    id: 'algal_bloom',
    when: { kind: 'population', species: S.lakeAlgae, op: '>', value: 0.9 },
    sustainedFor: 500,
    after: 150,
    chain: ['lakefish_overfished'],
    then: [{ kind: 'populationRate', species: S.lakeFish, multiplier: 0.5, durationTicks: 8_000 }],
    narrative: 'A green slick has spread across the lake surface.',
    severity: 'notable',
    blamedSpecies: S.lakeFish,
  },
  {
    id: 'water_poisoning',
    when: { kind: 'population', species: S.lakeAlgae, op: '>', value: 1.0 },
    sustainedFor: 900,
    after: 250,
    chain: ['lakefish_overfished', 'algal_bloom'],
    then: [
      { kind: 'populationShock', species: S.riverOtter, fractionDelta: -0.2 },
      { kind: 'populationShock', species: S.marshHeron, fractionDelta: -0.2 },
    ],
    narrative: 'The water has turned foul; even the otters avoid the shallows now.',
    severity: 'major',
    blamedSpecies: S.lakeFish,
  },

  // Deforestation -> erosion -> flood risk. Narrative-only past the vegetation trigger — `world`
  // owns terrain and river geometry; `ecology` only reports what it can see happening to the land.
  {
    id: 'deforestation_onset',
    when: { kind: 'vegetation', op: '<', value: 0.3 },
    sustainedFor: 700,
    after: 200,
    then: [{ kind: 'vegetationDelta', delta: -0.03 }],
    narrative: 'Tree cover is thinning fast along the ridgeline.',
    severity: 'minor',
  },
  {
    id: 'soil_erosion',
    when: { kind: 'vegetation', op: '<', value: 0.2 },
    sustainedFor: 1_000,
    after: 300,
    chain: ['deforestation_onset'],
    then: [{ kind: 'vegetationDelta', delta: -0.04 }],
    narrative: 'Bare slopes are washing away with every rain.',
    severity: 'notable',
  },
  {
    id: 'river_flood_risk',
    when: { kind: 'vegetation', op: '<', value: 0.15 },
    sustainedFor: 1_400,
    after: 400,
    chain: ['deforestation_onset', 'soil_erosion'],
    then: [{ kind: 'populationShock', species: S.marshElk, fractionDelta: -0.1 }],
    narrative: 'Silt chokes the lower river; the old fords are unrecognisable after the last storm.',
    severity: 'major',
  },

  // Fire ecology: drought + lightning -> wildfire -> ash fertilization -> later abundance.
  {
    id: 'drought_dry_brush',
    when: { kind: 'vegetation', op: '<', value: 0.4 },
    sustainedFor: 1_500,
    after: 0,
    then: [],
    narrative: 'The undergrowth is tinder-dry this season.',
    severity: 'minor',
  },
  {
    id: 'fire_ignition',
    when: {
      kind: 'compound',
      op: 'AND',
      conditions: [
        { kind: 'weather', weather: 'storm' },
        { kind: 'vegetation', op: '>', value: 0.25 },
      ],
    },
    sustainedFor: 20,
    after: 20,
    chain: ['drought_dry_brush'],
    then: [{ kind: 'fire' }],
    narrative: 'Lightning finds dry brush. The hillside burns.',
    severity: 'catastrophic',
  },
  {
    id: 'fire_recovery_flourish',
    when: { kind: 'vegetation', op: '>', value: 0.6 },
    sustainedFor: 2_500,
    after: 400,
    chain: ['fire_ignition'],
    then: [{ kind: 'populationRate', species: S.meadowGrass, multiplier: 1.3, durationTicks: 6_000 }],
    narrative: 'Ash has fed the soil; the ridge is greener than it has been in years.',
    severity: 'notable',
  },

  // Scavengers track total death rate, and mass killing invites disease along their contact web.
  {
    id: 'carrion_surge',
    when: { kind: 'population', species: S.carrionCrow, op: '>', value: 0.75 },
    sustainedFor: 400,
    after: 100,
    then: [],
    narrative: 'Crows gather in unnatural numbers over the valley.',
    severity: 'minor',
    blamedSpecies: S.carrionCrow,
  },
  {
    id: 'disease_outbreak',
    when: { kind: 'population', species: S.carrionCrow, op: '>', value: 0.9 },
    sustainedFor: 700,
    after: 200,
    chain: ['carrion_surge'],
    then: [{ kind: 'populationShock', species: S.redDeer, fractionDelta: -0.15 }],
    narrative: 'Disease follows the dead. The deer herd is thinning from more than hunger.',
    severity: 'major',
  },
  {
    id: 'disease_spread_secondary',
    when: { kind: 'population', species: S.carrionCrow, op: '>', value: 0.95 },
    sustainedFor: 900,
    after: 300,
    chain: ['carrion_surge', 'disease_outbreak'],
    then: [{ kind: 'populationShock', species: S.wildBoar, fractionDelta: -0.15 }],
    narrative: 'The sickness has jumped to the boar as well.',
    severity: 'major',
  },
];
