import { SPECIES_IDS as S } from './species.data';
import type { NatureRule } from './rules.types';

export const SOCIAL_RULES: NatureRule[] = [
  // Overhunted herbivores -> predators turn to livestock -> village hostility toward wildlife.
  {
    id: 'herbivore_overhunted_hare',
    when: { kind: 'playerKills', species: S.hare, op: '>', value: 8 },
    sustainedFor: 50,
    after: 100,
    then: [{ kind: 'populationRate', species: S.lynx, multiplier: 0.85, durationTicks: 6_000 }],
    narrative: 'Hunters have thinned the hares badly. The lynx are going hungry.',
    severity: 'minor',
    blamedSpecies: S.hare,
  },
  {
    id: 'herbivore_overhunted_deer',
    when: { kind: 'playerKills', species: S.redDeer, op: '>', value: 10 },
    sustainedFor: 50,
    after: 100,
    then: [{ kind: 'populationRate', species: S.greyWolf, multiplier: 0.8, durationTicks: 6_000 }],
    narrative: 'The deer herds are noticeably thinner than they were a season ago.',
    severity: 'notable',
    blamedSpecies: S.redDeer,
  },
  {
    id: 'herbivore_overhunted_boar',
    when: { kind: 'playerKills', species: S.wildBoar, op: '>', value: 8 },
    sustainedFor: 50,
    after: 100,
    then: [],
    narrative: 'Boar sign has grown scarce along the forest paths.',
    severity: 'minor',
    blamedSpecies: S.wildBoar,
  },
  {
    id: 'village_hostility_wolves',
    when: { kind: 'population', species: S.greyWolf, op: '<', value: 0.3 },
    sustainedFor: 800,
    after: 300,
    chain: ['herbivore_overhunted_deer'],
    then: [],
    narrative: 'With deer scarce, wolves have started circling the sheepfold instead.',
    severity: 'major',
    blamedSpecies: S.greyWolf,
  },
  {
    id: 'village_hostility_jackals',
    when: { kind: 'playerKills', species: S.dustAntelope, op: '>', value: 8 },
    sustainedFor: 200,
    after: 300,
    then: [{ kind: 'populationRate', species: S.desertJackal, multiplier: 0.85, durationTicks: 6_000 }],
    narrative: 'Jackals have been seen prowling the badlands settlements at dusk.',
    severity: 'notable',
    blamedSpecies: S.dustAntelope,
  },

  // Overhunting an apex predator destabilises everything beneath it, not just its prey.
  {
    id: 'apex_overhunted_direwolf',
    when: { kind: 'playerKills', species: S.direWolf, op: '>', value: 2 },
    sustainedFor: 100,
    after: 200,
    then: [{ kind: 'populationRate', species: S.greyWolf, multiplier: 1.2, durationTicks: 8_000 }],
    narrative: 'Something apex has been struck down. The forest\'s balance wavers.',
    severity: 'major',
    blamedSpecies: S.direWolf,
  },
  {
    id: 'apex_overhunted_cavebear',
    when: { kind: 'playerKills', species: S.caveBear, op: '>', value: 2 },
    sustainedFor: 100,
    after: 200,
    then: [{ kind: 'populationRate', species: S.lynx, multiplier: 1.2, durationTicks: 8_000 }],
    narrative: 'The high passes feel emptier without the cave bear watching them.',
    severity: 'major',
    blamedSpecies: S.caveBear,
  },
  {
    id: 'apex_overhunted_swampwyrm',
    when: { kind: 'playerKills', species: S.swampWyrm, op: '>', value: 2 },
    sustainedFor: 100,
    after: 200,
    then: [{ kind: 'populationRate', species: S.riverOtter, multiplier: 1.2, durationTicks: 8_000 }],
    narrative: 'The marsh no longer holds its breath at dusk.',
    severity: 'major',
    blamedSpecies: S.swampWyrm,
  },

  // Keystone species whose loss silently restructures a region — no single dramatic event, just
  // a region that quietly stops working the way it used to.
  {
    id: 'keystone_loss_wolf_silent',
    when: { kind: 'population', species: S.greyWolf, op: '<', value: 0.05 },
    sustainedFor: 4_000,
    after: 1_000,
    chain: ['wolf_collapse'],
    then: [{ kind: 'populationRate', species: S.redDeer, multiplier: 1.1, durationTicks: 10_000 }],
    narrative: 'This region has quietly stopped being what it was. Nobody can point to the day it changed.',
    severity: 'catastrophic',
    blamedSpecies: S.greyWolf,
    once: true,
  },
  {
    id: 'keystone_loss_bee_silent',
    when: { kind: 'population', species: S.meadowBee, op: '<', value: 0.05 },
    sustainedFor: 4_000,
    after: 1_000,
    chain: ['bee_collapse'],
    then: [{ kind: 'populationRate', species: S.berryShrub, multiplier: 0.4, durationTicks: 10_000 }],
    narrative: 'The meadow still looks green. It just doesn\'t smell like flowers anymore.',
    severity: 'major',
    blamedSpecies: S.meadowBee,
    once: true,
  },
  {
    id: 'keystone_loss_berry_silent',
    when: { kind: 'population', species: S.berryShrub, op: '<', value: 0.05 },
    sustainedFor: 4_000,
    after: 1_000,
    then: [{ kind: 'populationRate', species: S.wildBoar, multiplier: 0.5, durationTicks: 10_000 }],
    narrative: 'The forest floor has gone bare where the shrubs used to grow.',
    severity: 'major',
    blamedSpecies: S.berryShrub,
    once: true,
  },

  // Positive cascades: protect a species long enough and the region visibly flourishes.
  {
    id: 'protect_wolves_flourish',
    when: {
      kind: 'compound',
      op: 'AND',
      conditions: [
        { kind: 'population', species: S.greyWolf, op: '>', value: 0.8 },
        { kind: 'playerKills', species: S.greyWolf, op: '<', value: 1 },
      ],
    },
    sustainedFor: 5_000,
    after: 1_000,
    then: [{ kind: 'populationRate', species: S.meadowGrass, multiplier: 1.15, durationTicks: 10_000 }],
    narrative: 'The wolves have held this ground for a long while now, and the land is richer for it.',
    severity: 'notable',
    once: true,
  },
  {
    id: 'protect_bee_flourish',
    when: {
      kind: 'compound',
      op: 'AND',
      conditions: [
        { kind: 'population', species: S.meadowBee, op: '>', value: 0.8 },
        { kind: 'playerKills', species: S.meadowBee, op: '<', value: 1 },
      ],
    },
    sustainedFor: 5_000,
    after: 1_000,
    then: [{ kind: 'populationRate', species: S.berryShrub, multiplier: 1.25, durationTicks: 10_000 }],
    narrative: 'The meadow hums with bees again, and the shrubs are heavy with fruit.',
    severity: 'notable',
    once: true,
  },
  {
    id: 'badlands_overgrazing',
    when: { kind: 'population', species: S.dustAntelope, op: '>', value: 0.85 },
    sustainedFor: 500,
    after: 150,
    then: [{ kind: 'populationRate', species: S.thornbrush, multiplier: 0.7, durationTicks: 6_000 }],
    narrative: 'The antelope herds have grown bold, and the thornbrush is thinning for it.',
    severity: 'notable',
  },
  {
    id: 'badlands_desertification',
    when: { kind: 'vegetation', op: '<', value: 0.1 },
    sustainedFor: 1_500,
    after: 400,
    chain: ['badlands_overgrazing'],
    then: [{ kind: 'populationShock', species: S.dustAntelope, fractionDelta: -0.2 }],
    narrative: 'The badlands have turned harder still — even the thornbrush struggles here now.',
    severity: 'major',
  },
];
